### ISSUE TITLE
Convert Cargo.toml files to use `workspace` dependency trees

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/syncstorage-rs#1461]
Cargo now allows sub-crates to use [workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html). 
At the least, we should copy the `[package]` values down from a central Cargo.toml file.

e.g. in `syncserver-common` specify

```toml
[package]
name  = "syncserver-common"
version.workspace=true
edition.workspace=true
authors.workspace=true
```

This would ensure that all crates are updated to the latest version when the central `syncstorage-rs/Cargo.toml` file is.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DISCO-2245)
